package chris;

import java.nio.file.Path;

import chris.exception.ChrisException;
import chris.parser.CommandType;
import chris.parser.Parser;
import chris.storage.Storage;
import chris.task.Task;
import chris.task.TaskList;
import chris.ui.Ui;

/**
 * Coordinates the chatbot's UI, task list, parser, and storage components.
 */
public class Chris {
    private final Ui ui;
    private final Storage storage;
    private final TaskList tasks;
    private boolean isExitRequested;

    /**
     * Creates a chatbot that stores tasks at the default relative data-file path.
     */
    public Chris() {
        this(Path.of("data", "chris.txt"));
    }

    /**
     * Creates a chatbot that stores tasks at the specified file path.
     *
     * @param filePath Path to the task data file.
     */
    public Chris(Path filePath) {
        this.ui = new Ui();
        this.storage = new Storage(filePath);
        this.tasks = loadTasks();
    }

    /**
     * Runs the chatbot command loop until the user exits or input ends.
     */
    public void run() {
        this.ui.showWelcome();

        while (!this.isExitRequested && this.ui.hasNextCommand()) {
            String input = this.ui.readCommand();
            this.ui.showLine();
            this.ui.showMessage(getResponse(input));
            this.ui.showLine();
        }
        this.ui.close();
    }

    /**
     * Processes one command and returns the response for either user interface.
     *
     * @param input Command entered by the user.
     * @return Response generated by the chatbot.
     */
    public String getResponse(String input) {
        try {
            return executeCommand(input.trim());
        } catch (ChrisException exception) {
            return this.ui.formatError(exception.getMessage());
        }
    }

    /**
     * Returns whether the user has entered the {@code bye} command.
     *
     * @return {@code true} if the application should exit.
     */
    public boolean isExitRequested() {
        return this.isExitRequested;
    }

    /**
     * Returns the greeting displayed when the GUI opens.
     *
     * @return Chatbot greeting and banner.
     */
    public String getWelcomeMessage() {
        return this.ui.getWelcomeMessage();
    }

    private String executeCommand(String input) throws ChrisException {
        CommandType commandType = Parser.parseCommandType(input);
        return switch (commandType) {
            case BYE -> {
                this.isExitRequested = true;
                yield this.ui.getGoodbyeMessage();
            }
            case LIST -> this.ui.formatTaskList(this.tasks);
            case FIND -> this.ui.formatMatchingTasks(this.tasks.find(Parser.parseFindKeyword(input)));
            case MARK -> markTask(input, commandType);
            case UNMARK -> unmarkTask(input, commandType);
            case DELETE -> deleteTask(input, commandType);
            case TODO -> addTask(Parser.parseTodo(input));
            case DEADLINE -> addTask(Parser.parseDeadline(input));
            case EVENT -> addTask(Parser.parseEvent(input));
            case UNKNOWN -> throw new ChrisException("I don't recognize that command. "
                    + "Try todo, deadline, event, list, find, mark, unmark, delete, or bye.");
            default -> throw new AssertionError("Unhandled command type: " + commandType);
        };
    }

    private String markTask(String input, CommandType commandType) throws ChrisException {
        int taskIndex = Parser.parseTaskIndex(input, commandType.getCommandWord(), this.tasks.size());
        Task markedTask = this.tasks.mark(taskIndex);
        saveTasks();
        return this.ui.formatTaskMarked(markedTask);
    }

    private String unmarkTask(String input, CommandType commandType) throws ChrisException {
        int taskIndex = Parser.parseTaskIndex(input, commandType.getCommandWord(), this.tasks.size());
        Task unmarkedTask = this.tasks.unmark(taskIndex);
        saveTasks();
        return this.ui.formatTaskUnmarked(unmarkedTask);
    }

    private String deleteTask(String input, CommandType commandType) throws ChrisException {
        int taskIndex = Parser.parseTaskIndex(input, commandType.getCommandWord(), this.tasks.size());
        Task removedTask = this.tasks.delete(taskIndex);
        saveTasks();
        return this.ui.formatTaskDeleted(removedTask, this.tasks.size());
    }

    private String addTask(Task task) throws ChrisException {
        this.tasks.add(task);
        saveTasks();
        return this.ui.formatTaskAdded(task, this.tasks.size());
    }

    private void saveTasks() throws ChrisException {
        this.storage.saveTasks(this.tasks.asList());
    }

    private TaskList loadTasks() {
        try {
            return new TaskList(this.storage.loadTasks());
        } catch (ChrisException exception) {
            this.ui.showError(exception.getMessage());
            return new TaskList();
        }
    }

    /**
     * Starts the chatbot using the default relative data-file path.
     *
     * @param args Command-line arguments; not used.
     */
    public static void main(String[] args) {
        new Chris().run();
    }
}
